### ISSUE TITLE
Main logo should be vertically aligned

### ISSUE THREAD

**Issue by willmot** [humanmade/hmn-handbook#3]
In the left sidebar the main logo should be vertically aligned so its always in the center

![screen shot 2014-04-14 at 13 02 40](https://cloud.githubusercontent.com/assets/308507/2694945/c6012cd2-c3cc-11e3-929d-8209fa651eae.png)

**Comment by richardswain** [comment]
Fixed in https://github.com/humanmade/hmn-handbook/pull/17
