### ISSUE TITLE
Ability to comment inline on content

### ISSUE THREAD

**Issue by willmot** [humanmade/hmn-handbook#4]
Probably using https://github.com/rmccue/InlineComments

**Comment by richardswain** [comment]
@willmot Unfortunately couldn't get @rmccue plugin to work.

Tried "inline-comments" plugin.

Maybe needs some styling?

There is count of comments in a bubble, and the comment bubble can be "+" or "bubble" on hover or not. Various other options in the plugin settings.

Is this what you wanted?

![human_made_client_rates___handbook](https://cloud.githubusercontent.com/assets/888319/7278928/55aeb322-e910-11e4-85aa-0f0aaa7adc0a.png)

**Comment by willmot** [comment]
Yeah this looks like a good improvement. Can this go live and then we can iterate on the design or is it so broken we need to style it first?

**Comment by richardswain** [comment]
yup, see https://github.com/humanmade/Human-Made-website/pull/581

**Comment by willmot** [comment]
Deployed.

**Comment by willmot** [comment]
This seems to work pretty nicely, nice one @richardswain. Let's open new issues for changes.
